name: Azure Backend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # Login to ACR
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: portregistryindia.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Build and Push Backend Docker Image
    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: portregistryindia.azurecr.io/port-backend:${{ github.sha }}
    
    # Deploy Backend to Azure Container Instances
    - name: Deploy Backend to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: port-resources-india
        dns-name-label: port-backend-${{ github.run_number }}
        image: portregistryindia.azurecr.io/port-backend:${{ github.sha }}
        registry-login-server: portregistryindia.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: port-backend
        location: 'centralindia'
        ports: 80
        secure-environment-variables: ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} 